### ISSUE TITLE
errpr when trying to switch region

### ISSUE THREAD

**Issue by Belialeral** [ecochia/ecochia-wiki#3]
Hi everyone, i've tried following the wiki but when i type in the command  ./chia plotnft join -u https://northamerica.ecochia.io -i 2 i get the following error:

PS C:\Users\Plotter\AppData\Local\Chia-Blockchain\app-1.2.2\resources\app.asar.unpacked\daemon> ./chia plotnft join -u https://northamerica.ecochia.io -i 2
Incorrect version: 1, should be 1
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000012B2007B430>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 746, in call_soon
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

what can i do to solve it? thanks in advance

**Comment by ohld** [comment]
You need to wait for the node & wallet to sync. Also check that you are using the latest [Chia](https://www.chia.net/download/) client.

**Comment by Ealrann** [comment]
Similar error here. Everything is synced, up-to-date and working, lots of plots, but I cannot join ecochia pool:

 ```
chia plotnft join -i 2 -u https://europe.ecochia.io
Incorrect version: 1, should be 1
```
